[supabase]
url = "https://hwfsggjzsujuhlcbvlzr.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3ZnNnZ2p6c3VqdWhsY2J2bHpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0NDkwODIsImV4cCI6MjA4NTAyNTA4Mn0.2q6_hiXsJitgVWCNkQAszyY0pnOIG_0svxcXlMV3Ey0"